"""Core event data models.

These are intentionally simple dataclasses with full type annotations
to facilitate a potential Rust rewrite later.
"""

from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from typing import Optional


class Severity(Enum):
    """Alert severity levels."""
    INFO = "info"
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    CRITICAL = "critical"


@dataclass(frozen=True, slots=True)
class DNSEvent:
    """A DNS query event from Pi-hole or similar resolver."""

    timestamp: datetime
    client: str  # IP address or hostname
    domain: str
    query_type: str  # A, AAAA, CNAME, etc.
    blocked: bool
    upstream: Optional[str] = None  # Which upstream resolver was used
    response_time_ms: Optional[float] = None

    def domain_parts(self) -> list[str]:
        """Split domain into parts for analysis."""
        return self.domain.lower().split(".")


@dataclass(frozen=True, slots=True)
class ConnectionEvent:
    """A network connection event from OpenWRT or host agent."""

    timestamp: datetime
    client: str  # Source IP or hostname
    src_port: int
    dst_ip: str
    dst_port: int
    protocol: str  # tcp, udp, icmp
    bytes_sent: int = 0
    bytes_recv: int = 0
    duration_seconds: Optional[float] = None
    dns_domain: Optional[str] = None  # Correlated DNS lookup if known


@dataclass(frozen=True, slots=True)
class ProcessNetworkEvent:
    """A process-level network event from a host agent."""

    timestamp: datetime
    host: str  # Hostname of the monitored machine
    process_name: str
    pid: int
    exe_path: str
    user: str
    cmdline: str
    parent_pid: Optional[int]
    parent_name: Optional[str]
    connection: ConnectionEvent
    authorized: Optional[bool] = None  # None if not yet checked


@dataclass(slots=True)
class Alert:
    """An alert generated by the analysis engine."""

    id: str
    timestamp: datetime
    severity: Severity
    title: str
    description: str
    source_event_type: str  # "dns", "connection", "process"
    source_event_id: Optional[str] = None
    client: Optional[str] = None
    domain: Optional[str] = None
    dst_ip: Optional[str] = None
    process_name: Optional[str] = None

    # Analysis metadata
    analyzer: str = ""  # Which analyzer generated this
    confidence: float = 0.0  # 0.0 to 1.0
    llm_analysis: Optional[str] = None  # If escalated to LLM

    # Tracking
    acknowledged: bool = False
    false_positive: bool = False
    notes: str = ""
    tags: list[str] = field(default_factory=list)
